config/routes.rb
Rails.application.routes.draw do

  root 'entries#index'
  resources :entries

  get '/login' => 'session#new'
  post '/session' => 'session#create'

  # scope 'admin' do
  #   resources :entries
  # end

  get '/admin' => 'admin#show'

  delete '/session' => 'session#destroy'

end

app/models/entry.rb
class Entry < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  # has_many :entries

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  def show

    @entries = Entry.all

    @user = User.find_by(id: session[:user_id])
    if @user && @user.admin_status == "t"
        render :show
    else
        redirect_to '/login'
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @entries = Entry.all
    @user = User.find_by(id: session[:user_id])
  end

  def show
    @user = User.find_by(id: session[:user_id])
    @entry = Entry.find_by(id: params[:id])
  end

  def new
    @user = User.find_by(id: session[:user_id])
    if @user && @user.admin_status == "t"
      @entry = Entry.new
    else
      redirect_to '/'
    end
  end

  def create
    @entry = Entry.create(entry_params)
    redirect_to @entry
  end

  def edit
    @user = User.find_by(id: session[:user_id])
    if @user && @user.admin_status == "t"
      @entry = Entry.find_by(id: params[:id])
    else
      redirect_to '/'
    end
  end

  def update
    @entry = Entry.find_by(id: params[:id])
    @entry.update_attributes(entry_params)
    redirect_to @entry
  end

  def destroy
    @user = User.find_by(id: session[:user_id])
    if @user && @user.admin_status == "t"
      @entry = Entry.find_by(id: params[:id])
      @entry.destroy
      redirect_to entries_path
    else
      redirect_to '/'
    end
  end

  private
  def entry_params
    params.require(:entry).permit(:title, :content)
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
    render :new
  end

  def create
       user = User.find_by(username: params[:username])

       if user && user.authenticate(params[:password]) && user.admin_status == "t"
           session[:user_id] = user.id
           redirect_to '/admin'

       elsif user && user.authenticate(params[:password]) && user.admin_status == "f"
           session[:user_id] = user.id
           redirect_to '/'

       else
           @error = true
           redirect_to '/login'
       end
   end

  def destroy
       reset_session
       redirect_to '/'
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/show.html.erb
<div class="jumbotron">
  <div class="container">
    <nav>
      <a href="/"><i class="fa fa-home fa-2x"></i></a>
    </nav>
    <div class="logout">
      <% if @user %>
        <a href="/admin" class="btn btn-default">Admin</a>
        <form method="POST" action="/session">
          <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
          <input name="_method" value="DELETE" type="hidden">
          <button class="btn btn-default">Logout</button>
        </form>
      <% end %>
    </div>
    <h1> Hello, <%= @user.username %> </h1>
    <button class="btn btn-default"><%= link_to 'Create Post', new_entry_path %></button>
  </div>
</div>

<div class="container">
  <div class="row">

  <% @entries.reverse_each do |entry| %>
  <div class="col-sm-4 admin-entries">
   <h2><%= link_to entry.title, entry %></h2>
   <p>Created: <%= entry.created_at.localtime.strftime("%b %d, %Y - %l:%M %P") %></p>
   <p>Last Updated: <%= entry.updated_at.localtime.strftime("%b %d, %Y - %l:%M %P") %></p>
  </div>
  <% end %>

  </div>
</div>

app/views/entries/edit.html.erb
<%= form_for @entry, url: {action: 'update'} do |f| %>
<h2><%= f.label :title %></h2>
<%= f.text_field :title, value: @entry.title %>

<h2><%= f.label :content %></h2>
<%= f.text_area :content, value: @entry.content %>
<br>

<%= f.submit %>
<% end %>
<%= link_to 'cancel', @entry %>

app/views/entries/index.html.erb
<div class="jumbotron home">
  <div class="container">
    <nav>
      <a href="/"><i class="fa fa-home fa-2x"></i></a>
    </nav>
    <div class="logout">
      <% if @user %>
        <a href="/admin" class="btn btn-default">Admin</a>
        <form method="POST" action="/session">
          <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
          <input name="_method" value="DELETE" type="hidden">
          <button class="btn btn-default">Logout</button>
        </form>
      <% end %>
    </div>
    <h1> Bacon and Eggs </h1>
    <h3> A Blog By Ron Swanson </h3>
  </div>
</div>

<div class="container">
  <div class="row">
  <% @entries.reverse_each do |entry| %>
    <div class="col-sm-8 col-sm-offset-2 home-entries">
      <h2><%= link_to entry.title, entry %></h2>
      <p class="preview"><%= entry.content[0, 200] + " . . ." %></p>
      <p class="timestamp"><%= entry.created_at.localtime.strftime("%b %d, %Y") %></p>
    </div>
  <% end %>
  </div>
</div>

app/views/entries/new.html.erb
<%= form_for @entry, url: {action: 'create'} do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<br /><br />

<%= f.label :content %>
<%= f.text_area :content %>
<br /><br />

<%= f.submit %>
<% end %>

<a href="/admin">Home</a>

app/views/entries/show.html.erb
<div class="jumbotron">
  <div class="container">
    <nav>
      <a href="/"><i class="fa fa-home fa-2x"></i></a>
    </nav>
    <div class="logout">
      <% if @user %>
        <a href="/admin" class="btn btn-default">Admin</a>
        <form method="POST" action="/session">
          <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
          <input name="_method" value="DELETE" type="hidden">
          <button class="btn btn-default">Logout</button>
        </form>
      <% end %>
    </div>
    <h1> <%= @entry.title %> </h1>
    <p class="timestamp"><%= @entry.created_at.localtime.strftime("%b %d, %Y") %></p>
    <% if @user && @user.admin_status == "t" %>
    <button class="btn btn-default"><%= link_to 'Edit', edit_entry_path(@entry) %></button>
    <button class="btn btn-default"><%= link_to 'Delete', @entry, method: :delete %></button>
    <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2">
      <p><%= @entry.content %></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bacon and Eggs</title>
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

  <!-- Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
</body>
</html>

app/views/secret/show.html.erb
<h1> Blog </h1>

<% @entries.reverse_each do |entry| %>
 <h2><%= link_to entry.title, entry %></h2>
 <p><%= entry.created_at %></p>
<% end %>

<h2> Hello, <%= @user.username %> </h2>
<p> Status: <%= @user.admin_status %></p>

<form method="POST" action="/session">
    <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
    <input name="_method" value="DELETE" type="hidden">
    <button>Logout</button>
</form>

app/views/session/new.html.erb
<div class="jumbotron">
  <div class="container">
    <nav>
      <a href="/"><i class="fa fa-home fa-2x"></i></a>
    </nav>

    <h1> Admin Login </h1>

  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <form action="/session" method="POST" class="admin-login">
      <div class="form-group">
        <label for="username"> Username: </label>
        <input name="username" type="text">
      </div>
      <div class="form-group">
        <label for="password"> Password: </label>
        <input name="password" type="password">
      </div>
        <input name="authenticity_token" value="<%= form_authenticity_token() %>" type="hidden">
        <button class="btn btn-default">Sign In</button>
    </form>
  </div>
</div>
</div>